on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 */1 * *'

name: CI

jobs:
  Configure:
    name: Configure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          repository: php/php-src
          ref: master
          fetch-depth: 2
      - run: mkdir .git_tmp
      - run: echo "PHP-master" > .git_tmp/configure.sh
      - run: cd ../php-src ; ./buildconf --force
      - run: cd ../php-src ; ./configure --help >> ../configure/.git_tmp/configure.sh
      - name: sync
        if: github.event_name == 'push' || github.event_name == 'schedule'
        uses: docker://pcit/pages
        env:
          PCIT_EMAIL: khs1994@khs1994.com
          PCIT_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PCIT_GIT_URL: github.com/${{ github.repository }}
          PCIT_KEEP_HISTORY: "1"
          PCIT_LOCAL_DIR: .git_tmp
          PCIT_MESSAGE: Sync from khs1994-php/configure@${{github.sha}} by PCIT
          PCIT_TARGET_BRANCH: pre
          PCIT_USERNAME: khs1994
